### ISSUE TITLE
ERROR DEPOLY

### ISSUE THREAD

**Issue by Adhaaz** [ayMissouri/aWatch#1]
Sir, I encountered an error when deploying this project to Vercel. Can you provide a way to resolve this error?
![Screenshot_2023-08-31-18-29-37-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ayMissouri/aWatch/assets/75169859/aedcd9aa-44b9-4969-810a-aed42be0f8ad)

**Comment by ayMissouri** [comment]
Use `npm install --force` as the install command.
